### ISSUE TITLE
Interpolate dep is not up to date

### ISSUE THREAD

**Issue by victorcoder** [buildkite/ecs-run-task#14]
`EnvFromSlice` method doesn't exists in the upstream github.com/buildkite/interpolate

**Comment by lox** [comment]
Are you seeing an error in `ecs-run-task` @victorcoder?

**Comment by victorcoder** [comment]
I'm trying to use `ecs-run-taks` as a lib for my project, and I'm using go module, interpolate is imported by go modules as an *indirect* dependency but it's pulling from master. 

This renders in this compilation failure: `../../../../pkg/mod/github.com/buildkite/ecs-run-task@v0.0.0-20180814012926-2cc084aaf0cc/parser/parse.go:20:3: undefined: interpolate.EnvFromSlice`

go modules doesn't use the vendor folder of the imported dependencies so the transitive dependencies should be pinned in the direct dependency or work with master.

Hope it clarifies the issue. I'm trying to find a workaround.

**Comment by victorcoder** [comment]
I just pined the version to the specific commit in `interpolate` but makes me think that if there is improvements in the library that `ecs-run-task` is not getting 🤷‍♀️
