### ISSUE TITLE
Support running tasks using existing task definitions

### ISSUE THREAD

**Issue by mikeocool** [buildkite/ecs-run-task#5]
Hey there -- happy to do the work to make this possible, but want to make sure I'm headed in the right direction.

Basically I'm imaginging something along the lines of:
`ecs-run-task --task-definition existing-task:1234 echo "Hello from Docker!"`

And ecs-run-task would skip the process of registering a new task definition, and just use the one provided.

Use cases for this that I've come across for this:

In our CI pipeline:
1) Register an updated task definition version
2) Run a task using ecs-run-task, using what is essentially the same task definition
3) Update an ECS Service with the task registered in step 1

Right now, every CI run results in the task definition version incrementing twice, since we register the new version and then use ecs-run-task, which registers another one.

Additionally, we still have the occasional task one-off task that needs to get run on production. Previous to Docker/ECS, running this involved SSHing into a production server and running a CLI command that is a part of the deployed codebase.

We've replaced that process using ecs-run-task to run those one off tasks, however right now you have to take the extra step of making sure the JSON you are providing to ecs-run-task is the same as the currently deployed task definition. It would be great to just use that already defined task definition.

**Comment by lox** [comment]
Sounds like a great idea @mikeocool! The only obstacle I can think of is that a logging driver needs to be set for the task so that it can be tailed. Unfortunately ECS run-task doesn't allow you to override log-driver, it has to be part of the task definition as far as I know.

Thoughts on whether that would make what you suggest unworkable? See https://github.com/buildkite/ecs-run-task/blob/master/runner/runner.go#L60-L72

**Comment by mikeocool** [comment]
Ahhh, I missed that piece when doing the exploratory work on this. I'll poke around a bit more and see if there's a different approach that might work, though that does seem like it makes this pretty unworkable.

Allowing additional overrides to task def parameters is being tracked here: https://github.com/aws/amazon-ecs-agent/issues/492

**Comment by lox** [comment]
Closing for now, I doubt this will be added upstream in the ecs-agent, frankly.
